version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gateway-node-final:
    build: ./gateway
    container_name: gateway-node-final
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./gateway:/app 
      - /app/node_modules  
    command: npm run dev
    depends_on: [users, products, orders]
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      USERS_TARGET: http://users:${USERS_PORT}
      PRODUCTS_TARGET: http://products:${PRODUCTS_PORT}
      ORDERS_TARGET: http://orders:${ORDERS_PORT}

  frontend-node-final:
    build: ./fe
    container_name: frontend-node-final
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app 
      - /app/node_modules
    depends_on:
      - gateway-node-final
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - API_URL=${API_URL}

  users:
    build: ./services/users
    container_name: users
    env_file: .env
    volumes:
      - ./services/users:/app 
      - /app/node_modules  
    command: npm run dev
    environment:
      PORT: ${USERS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: mongodb://${MONGO_HOST}:${MONGO_PORT}/usersdb
    depends_on: [mongo]

  products:
    build: ./services/products
    container_name: products
    env_file: .env
    volumes:
      - ./services/products:/app 
      - /app/node_modules  
    command: npm run dev
    environment:
      PORT: ${PRODUCTS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: mongodb://${MONGO_HOST}:${MONGO_PORT}/productsdb
    depends_on: [mongo]

  orders:
    build: ./services/orders
    container_name: orders
    env_file: .env
    volumes:
      - ./services/orders:/app 
      - /app/node_modules  
    command: npm run dev
    environment:
      PORT: ${ORDERS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: mongodb://${MONGO_HOST}:${MONGO_PORT}/ordersdb
      PRODUCTS_URL: ${PRODUCTS_URL}
    depends_on: [mongo, products]

volumes:
  mongo_data:
  
